参考: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

In NumPy dimensions are called axes. The number of axes is rank.

In [2]:
import numpy as np

In [3]:
a = np.arange(24).reshape(4, 6)

In [7]:
a.ndim, a.shape, a.dtype, a.itemsize, a.size

(2, (4, 6), dtype('int64'), 8, 24)

In [9]:
type(a), type(a[0])

(numpy.ndarray, numpy.ndarray)

创建 ndarray

以固定的大小或者固定的值初始化

In [19]:
np.zeros([2, 3], dtype=np.float32)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [20]:
np.ones([2, 2], dtype=np.complex)

array([[ 1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j]])

In [21]:
np.empty([3, 2])

array([[  3.10503618e+231,   4.33160578e-311],
       [  6.93056736e-310,   6.93056736e-310],
       [  3.10503618e+231,   3.10503618e+231]])

创建数字序列

In [22]:
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

获取浮点序列，并指定个数

In [30]:
a = np.linspace(0, np.pi, 8)

In [31]:
a, np.sin(a)

(array([ 0.        ,  0.44879895,  0.8975979 ,  1.34639685,  1.7951958 ,
         2.24399475,  2.6927937 ,  3.14159265]),
 array([  0.00000000e+00,   4.33883739e-01,   7.81831482e-01,
          9.74927912e-01,   9.74927912e-01,   7.81831482e-01,
          4.33883739e-01,   1.22464680e-16]))

In [45]:
a = np.arange(4).reshape(2, 2)
a

array([[0, 1],
       [2, 3]])

In [46]:
# element-size
a * a

array([[0, 1],
       [4, 9]])

In [47]:
# dot product
a.dot(a)

array([[ 2,  3],
       [ 6, 11]])

In [48]:
a = np.random.random([2, 3])

In [49]:
a

array([[ 0.27296607,  0.67788052,  0.38582667],
       [ 0.17564792,  0.38513258,  0.24766812]])

In [52]:
a.max()

0.67788051832715934

In [53]:
a.max(axis = 1)

array([ 0.67788052,  0.38513258])

In [55]:
a.max(axis = 0)

array([ 0.27296607,  0.67788052,  0.38582667])

In [58]:
a.sum(), a.sum(axis = 1), a.sum(axis = 0)

(2.1451218820502853,
 array([ 1.33667326,  0.80844862]),
 array([ 0.448614  ,  1.0630131 ,  0.63349478]))

In [60]:
# 累加和
a.cumsum(axis = 1)

array([[ 0.27296607,  0.95084659,  1.33667326],
       [ 0.17564792,  0.56078051,  0.80844862]])

## 常见函数

In [61]:
a

array([[ 0.27296607,  0.67788052,  0.38582667],
       [ 0.17564792,  0.38513258,  0.24766812]])

In [65]:
np.sqrt(a), np.exp(a), np.add(a, a)

(array([[ 0.52246155,  0.823335  ,  0.62114947],
        [ 0.41910372,  0.62059051,  0.49766265]]),
 array([[ 1.31385567,  1.96969856,  1.4708297 ],
        [ 1.1920183 ,  1.46980918,  1.28103471]]),
 array([[ 0.54593215,  1.35576104,  0.77165333],
        [ 0.35129585,  0.77026517,  0.49533623]]))

## Indexing, Slicing and Iterating

In [82]:
a = np.random.random([2, 4])
a

array([[ 0.44392099,  0.69088034,  0.34251081,  0.56709968],
       [ 0.47231264,  0.70991712,  0.39205951,  0.93685628]])

In [83]:
b = np.reshape(a, 8)
b[0:5:3] = 1.0
b

array([ 1.        ,  0.69088034,  0.34251081,  1.        ,  0.47231264,
        0.70991712,  0.39205951,  0.93685628])

In [91]:
b[-1], b[:-1], b[::-1]

(0.93685628299993318,
 array([ 1.        ,  0.69088034,  0.34251081,  1.        ,  0.47231264,
         0.70991712,  0.39205951]),
 array([ 0.93685628,  0.39205951,  0.70991712,  0.47231264,  1.        ,
         0.34251081,  0.69088034,  1.        ]))

In [93]:
for x in a.flat:
    print x

1.0
0.690880340743
0.342510812793
1.0
0.47231264141
0.709917123798
0.392059506465
0.936856283
